### ISSUE TITLE
Doesn't seem to work on Netflix

### ISSUE THREAD

**Issue by BenoitMaisonny** [jswanner/DontFuckWithPaste#100]
Text selection and copying is blocked on Netflix for descriptions of programmes, cast, and such. This extension doesn't seem to work on that site. You need an account and be logged in to see programme descriptions. DevTools shows that the text is there in clear in the HTML, so that's a workaround for copying.

**Comment by jswanner** [comment]
@BenoitMaisonny, thanks for reporting this issue. Netflix in this scenario is not actually preventing copy nor paste, but as you said is preventing text selection. They are doing so with CSS, by applying `user-select: none` on the `<body>`. I agree that it's hard to copy text when you can't select it, but prevention of text selection is not something this extension tries to address. I think you'd be better off using something like [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb?hl=en) to address this problem.
