### ISSUE TITLE
[Website Request] Publisher's Clearing House

### ISSUE THREAD

**Issue by pogue** [jswanner/DontFuckWithPaste#110]
The website, Publishers Clearing House, blocks paste when you try and paste your email and password in for the 2nd time. I searched the source of the page, but couldn't figure out how they were blocking paste.

The link to register is here:
https://accounts.pch.com/register?adt=cxSaO5JvtgEs3QZObPAztUgctLUqebpjEibmA3YKLynwWj5Pt2L2LhYg9yA3WKLQnwNNVSAIWIDNFQ

Here is a pastebin of the website:
https://pastebin.com/bMZYyDu9

But, if you could add this to your extension it would be greatly appreciated. I already contacted support on PCH.com and sent them a link to this article:

https://www.wired.com/2015/07/websites-please-stop-blocking-password-managers-2015/

Thank you for your time,
pogue

**Comment by jswanner** [comment]
@pogue, if you [activate the extension for that site](https://github.com/jswanner/DontFuckWithPaste#usage) then it will allow you to paste in the password confirmation field.
