### ISSUE TITLE
Doesn't work in intercom.io

### ISSUE THREAD

**Issue by Nowaker** [jswanner/DontFuckWithPaste#13]
I know I can blacklist a domain but maybe it makes sense to look up why it doesn't work there and come up with a solution that would fix Intercom and a variety of other websites.

**Comment by jswanner** [comment]
I'm sorry to hear you are having trouble with this extension. Can you be more specific about what's not working?

**Comment by Nowaker** [comment]
I'm sorry about that. ^V doesn't work in Intercom.io. Pasted text shows up and then immediately disappears.

**Comment by jswanner** [comment]
With the release of version 2, the extension is no longer active on Intercom (or any site) by default, which should alleviate this problem.
