### ISSUE TITLE
Chrome 49 : content.js "SyntaxError: Unexpected token { in line 6"

### ISSUE THREAD

**Issue by nomennescio** [jswanner/DontFuckWithPaste#26]
The script is broken on Chrome 49. The JavaScript console shows
content.js "SyntaxError: Unexpected token { in line 6"

line 6 has
chrome.storage.sync.get(window.defaultValues, function({exclude, include}) {
  const excludes = new RegExp(exclude.split('\n').join('|'));

**Comment by jswanner** [comment]
Whoa. I didn't think anyone would be using such an old version of Chrome, it was released over a year ago, with 9 major versions having been released since then. Is there something specifically keeping you on that version?

**Comment by jswanner** [comment]
Sorry, I won't be supporting any version of Chrome that doesn't support ECMAScript 2015... Didn't know you could still be running such an over version of Chrome, honestly.
