### ISSUE TITLE
Still Not Copying

### ISSUE THREAD

**Issue by 001aj** [jswanner/DontFuckWithPaste#28]
Hello, 
I've added the extension into chrome but it's still not working and I seriously need it. Please tell how it works.

**Comment by Thunder33345** [comment]
not the developer, AFAIK: it unregister events with copy and pasting
you should also list the sites which you encounter errors to help others fix it faster

**Comment by jasonjhofmann** [comment]
That is not a helpful bug report.  What version of Chrome are you using? Have you confirmed that the extension is enabled, not disabled?  Are you using Incognito mode? What is the URL of the site or sites you have tested it on?

**Comment by jswanner** [comment]
@Thunder33345 & @jasonjhofmann: Thanks for jumping in here and asking for additional information.

@001aj: There are many way that a site can effectively blocks you from copying content, this extension prevents the most direct form of copy blocking. If you provide more details, I will try to reproduce your problem.

That said, as long as the extension is configured correctly, if you are not able to copy content, the site is most likely hooking into more browser events, and there's not much I'm going to be able to do.

**Comment by 001aj** [comment]
@jasonjhofmann  I'm using Version 57.0.2987.133 (64-bit) of chrome. Neah, I'm not using Incognito mode. What sihnificant changes it reflect when the extension is enabled. I mean it always remains same, a D with grey background.   
@Thunder33345 I'm using it on simple coding websites.
@jswanner Well it's kind of environment where I get a question and I have to answer it, I can type it but it takes a lot of time.

**Comment by jswanner** [comment]
With the release of version 2 of this extension, it should be much easier to configure the extension to be active on particular sites, and provides visibility into the active/inactive state of the extension for any given site.

Without more context about the problem, I'm closing this issue for now.
