### ISSUE TITLE
doesnt work on ixel.in

### ISSUE THREAD

**Issue by vsreenathreddy1** [jswanner/DontFuckWithPaste#32]
it doesnt work in ixel.in

**Comment by Thunder33345** [comment]
please be specific on what did not work?
like what things does it break?
if you do have any issues, most cases you might just have to put them into the whitelisted list
as using this method to stop paste blocking can sometimes cause unintended consequences...

**Comment by jswanner** [comment]
@vsreenathreddy1 You probably want to update the extension's options to add ixel.in to the exclusions list.

- Open Chrome to: `chrome://extensions/?options=nkgllhigpcljnhoakjkgaieabnkmgdkb`
- Add `https?://.*?ixel.in/.*` to the second text box

For backwards compatibility with older versions of this extension, the default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. I've been wanting to change the extension to do just that, but that's still a work in progress.
