### ISSUE TITLE
Broken copying on CodePen and AWS Console

### ISSUE THREAD

**Issue by swoodford** [jswanner/DontFuckWithPaste#34]
**Issue:** 
Copying code on the following two websites and pasting into another text editor is broken with either a space, a dash, a box or nothing at all copied to the clipboard.

https://codepen.io/
https://console.aws.amazon.com/

**Browser:** Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
**Platform:** MacOS Sierra 10.12.5 (16F73)

**Solution:**
Had to whitelist both websites under Exclude URL Patterns:
`https?://.*?.?amazon.com/.*`
`https?://codepen.io/.*`

It took me a long time and a lot of frustration to realize this plugin was actually breaking copy/paste when it was supposed to fix it!  Maybe these two sites should be whitelisted in the plugin by default unless a solution can be found to avoid breaking copy functionality?

**Comment by jswanner** [comment]
For backwards compatibility with older versions, the default configuration of this extension is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones.

I have a complete rewrite of this extension to make that second style easier to work with; it's working, but still needs UX love. If you are familiar with using local extensions, you can test it out: https://github.com/jswanner/DontFuckWithPaste/tree/v2.

**Comment by ndbroadbent** [comment]
+1, I would like to see `https?://.*?.?amazon.com/.*` as a default rule. Haha, I just sent a very angry email to AWS customer support before I remembered that this extension was installed.

**Comment by jswanner** [comment]
The aforementioned version 2 has been released, which means the extension is no longer active on those sites by default.
