### ISSUE TITLE
Extension breaks pasting in Google Drive Spreadsheets 

### ISSUE THREAD

**Issue by eik3** [jswanner/DontFuckWithPaste#4]
When I have this extension enabled, I can't no longer Paste in Google Drive Spreadsheets. Neither Right-Click-Paste nor Menu Edit->Paste not Ctrl-V work.

Env:
Don't fuck with paste 0.2 from 2014-05-22
Chromium 37.0.2062.94 (Developer Build 290621) Ubuntu 12.04

**Comment by jswanner** [comment]
A new version of this extension has been pushed, which includes user-configurable settings for which sites this extension should run on.
