### ISSUE TITLE
Not working when pasting credit card number on Ebay

### ISSUE THREAD

**Issue by Zwitscherer** [jswanner/DontFuckWithPaste#40]
Hi,

I just wanted to update my profile on Ebay with my new credit card and I couldn't paste my credit card number into the field. Normally I let LastPass do this and it did paste at least the expiration date correctly, but couldn't paste the 16digit number. I then copied it from LastPass and tried to paste it manually but still no luck.

Tried this using Chrome 61.0.3163.100 on a Mac under macOS 10.13 (High Sierra).

**Comment by jswanner** [comment]
@Zwitscherer, how do you have this extension configured?

When viewing https://arbd.ebay.com/ws/eBayISAPI.dll?SetupCCPayment&from=piapp, I do see that they have `onpaste="return false;"` on the CC input field. Using the default settings, this extension is properly circumventing their paste-blocking for me.

**Comment by jswanner** [comment]
I'm closing this issue for now, it'll be reopened upon receipt of more information.
