### ISSUE TITLE
Can't save settings on Firefox 57 Beta 12 on macOS

### ISSUE THREAD

**Issue by alanorth** [jswanner/DontFuckWithPaste#41]
This plugin works great on Chrome but when I try it on Firefox it doesn't work. Looking at the settings, I see there are no defaults. I tried to add some regular expression like `.*` but they don't seem to stick, as they are gone when I close and re-open the settings.

![screen shot 2017-10-30 at 1 35 28 pm-fs8](https://user-images.githubusercontent.com/191754/32169037-795c8dba-bd77-11e7-98ef-c0fa7761a37b.png)

This is Firefox 57 Beta 12 on macOS 10.13.1 Beta if it helps.

**Comment by jswanner** [comment]
@alanorth, I'm not the one who published this extension for Firefox. Even if I'm able to fix the problem, I won't be able to update it on Firefox Marketplace.

**Comment by jswanner** [comment]
I'm not concerned with some republishing the code, but I would probably prefer that it were linked to a fork, if for nothing else so that issues could opened for it directly.

**Comment by alanorth** [comment]
Fair enough. I see there is a contact address for the author on the Addons page. I'll email the author and ask if they can fork this project and link to that one on their Addons page. Thanks, @jswanner.
