### ISSUE TITLE
Not working with DBS iBanking login

### ISSUE THREAD

**Issue by zhongwei-z** [jswanner/DontFuckWithPaste#42]
Browser using: Firefox 57
Version: 1.1
Website: https://internet-banking.dbs.com.sg/IB/Welcome
How to reproduce: Go to the above site, password field cannot be pasted into.

**Comment by jswanner** [comment]
@zhongwei-z, I'm not the one who published this extension for Firefox. Even if I'm able to fix the problem, I won't be able to update it on Firefox Marketplace.
