### ISSUE TITLE
Doesn't work with Moodle

### ISSUE THREAD

**Issue by Avamander** [jswanner/DontFuckWithPaste#43]
Would it be possible to add [Moodle](https://moodle.org/) support to this extension?

**Comment by jswanner** [comment]
@Avamander, you can configure the extension to not run on Moodle:

Go to chrome://extensions/?options=nkgllhigpcljnhoakjkgaieabnkmgdkb
In the 2nd box, labeled "Exclude URL Patterns", add `https://moodle\\.org/.*` on its own line.

For backwards compatibility with older versions of this extension, the default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. I've been wanting to change the extension to do just that, but I would want the experience of blacklisting a site to be much better, especially for non-technical people.

I have a complete rewrite of this extension to make that second style easier to work with; it's working, but still needs UX love. If you are familiar with using local extensions, you can test it out: https://github.com/jswanner/DontFuckWithPaste/tree/v2.
