### ISSUE TITLE
default exclusions

### ISSUE THREAD

**Issue by grahamperrin** [jswanner/DontFuckWithPaste#44]
You might like to add these: 

- `https?://riot.im/app/.*`
- `https?://riot.im/develop/.*`

**Comment by aaronraimist** [comment]
Does that bug only affect Waterfox and other older versions of Firefox? I know I used to see it but I don't see that bug on Firefox 58.

**Comment by grahamperrin** [comment]
Tested with Firefox 57.0.3 on Mac OS X 10.12.6: https://riot.im/app/#/room/#test:matrix.org does not work properly without the `https?://riot.im/app/.*` exclusion.

**Comment by jswanner** [comment]
I don't think constantly adding new patterns to the defaults is a reasonable solution, and it doesn't even help people that already have the extension installed.

For backwards compatibility with older versions of this extension, the default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. I've been wanting to change the extension to do just that, but I would want the experience of blacklisting a site to be much better, especially for non-technical people.

I have a complete rewrite of this extension to make that second style easier to work with; it's working, but still needs UX love. If you are familiar with using local extensions, you can test it out: https://github.com/jswanner/DontFuckWithPaste/tree/v2.
