### ISSUE TITLE
Causes newline to be stripped out when using Slack

### ISSUE THREAD

**Issue by botto** [jswanner/DontFuckWithPaste#45]
Hi,

I'm having an issue where a blob of text I have that uses newline characters is not pasting correctly in Slack.
I guess slack is doing something with the paste event and DFWP is stopping their paste event handler.

Maybe add a whitelist ability to extension?

Thanks

**Comment by jswanner** [comment]
See https://github.com/jswanner/DontFuckWithPaste/pull/46#issuecomment-358731512
