### ISSUE TITLE
This addon fucks with Firefox paste

### ISSUE THREAD

**Issue by maroux** [jswanner/DontFuckWithPaste#48]
Evidently, after this add-on, you can't copy (using either the keyboard short cut or right click menu), from certain `textarea` elements. It works fine for cut, oddly enough.

Examples:
https://rustbyexample.com/hello.html
https://ace.c9.io/

ps: I know this technically messes up copy, not paste, but couldn't resist the chance for that title 😛

**Comment by jswanner** [comment]
@maroux I'm not the one who published this extension for Firefox, and I wouldn't be able to update it on Firefox Marketplace.

**Comment by aaronraimist** [comment]
@jswanner I'm sorry they keep putting these issues on your GitHub page, I only link to my GitHub page from the Firefox addon store. Anyway this isn't a Firefox issue alone, the same issue is present in your original Chrome version. Possibly the same issue as #49?

**Comment by jswanner** [comment]
@aaronraimist The last time I tried the Firefox addon, the addon settings didn't work, and therefore I couldn't configure on which sites the addon should & shouldn't run. I just tried again, and it did work for me. Perhaps I was using Firefox Developer Edition before or something.

@maroux You can follow the instructions in #18 to configure the addon not to run on sites where you don't want it to: https://github.com/jswanner/DontFuckWithPaste/issues/18#issuecomment-258445594. The default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones.

**Comment by maroux** [comment]
@jswanner Ah sorry didn't realize you are not the publisher for the FF add-on. 

I saw some of those suggestions in other addon bugs. I'll try it, but I'm afraid it might not scale super well. I do agree, blacklist certain sites is a better model here.
