### ISSUE TITLE
Disables copy/paste in ShareLatex

### ISSUE THREAD

**Issue by ksonbol** [jswanner/DontFuckWithPaste#49]
Using this extension, copying and pasting (which normally works without a problem) does not work anymore in https://www.sharelatex.com inside the document editing part.

**Comment by Thunder33345** [comment]
please kindly just add that site to whitelist
not much we here can do then that

**Comment by jswanner** [comment]
For backwards compatibility with older versions of this extension, the default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. I've been wanting to change the extension to do just that, but I would want the experience of blacklisting a site to be much better, especially for non-technical people.

I have a complete rewrite of this extension to make that second style easier to work with; it's working, but still needs UX love. If you are familiar with using local extensions, you can test it out: https://github.com/jswanner/DontFuckWithPaste/tree/v2.
