### ISSUE TITLE
Broken "click here"

### ISSUE THREAD

**Issue by bcsteeve** [jswanner/DontFuckWithPaste#54]
I have a notification (Windows 7, Chrome [latest]).

"Don't Fuck With Paste 2.0
Version 2.0 is very different, click to learn more."

"Click" what?  Clicking anything in that notification does NOTHING.  Any chance you can give me the link to where that was supposed to take me?

**Comment by tambry** [comment]
Works for me on Windows 10. I needed to just click on the notification box.

**Comment by jswanner** [comment]
@bcsteeve sorry to hear that clicking on the notification (anywhere but the "Close" part of it) didn't work for you. I used the Chrome-supplied click handler to open a tab to the URL @tambry linked to.

**Comment by jswanner** [comment]
The notification is only meant to display once, and I have no future plans for other notifications, so I don't think it's worth spending time trying to understand what went wrong in this case. I'll be removing the notification and the permission in a future update anyway.
