### ISSUE TITLE
Any chance we can get this extension renamed

### ISSUE THREAD

**Issue by grumpy-curmudgeon** [jswanner/DontFuckWithPaste#56]
... to something that is work and family friendly? I REALLY don't need f-bomb appearing in my notifications when I'm projecting my screen in a meeting. Thanks for that.

(Also, unrelated, but I'll pile on that this update was totally unnecessary and a step backwards.)

**Comment by jswanner** [comment]
Please see https://github.com/jswanner/DontFuckWithPaste/issues/15#issuecomment-258460832
