### ISSUE TITLE
GET OUT OF MY CHROME HISTORY

### ISSUE THREAD

**Issue by brkorb** [jswanner/DontFuckWithPaste#57]
You have no business requiring access.

**Comment by jswanner** [comment]
I'm in the process of describing the change in more depth.

In the meantime, please see https://github.com/jswanner/DontFuckWithPaste/issues/52#issuecomment-372863598 for an explanation as to what the extension does with the `tabs` permission (which is the permission Chrome describes as meaning the extension has access to your browsing history).
