### ISSUE TITLE
Newest Version (Mid March 2018) Breaks Paste in Google Docs

### ISSUE THREAD

**Issue by klepper** [jswanner/DontFuckWithPaste#58]
Title.

**Comment by jswanner** [comment]
Is the extension active or inactive for you on Google Docs (is the icon grey or blue)? If active (blue), you can remove any rules matching the site by: clicking on the extension icon, then clicking the "x" button next to the rule.

That said, I cannot reproduce the error even with the extension active for Google Docs. If the above steps didn't help, can you provide more details as to what exactly is broken?

**Comment by jswanner** [comment]
If by Google Docs you meant Google Sheets, then I was able to reproduce the problem. But again, deleting any rules that match the URL should fix the problem. If that's not the case, feel free to reopen issue.

**Comment by michaelrkn** [comment]
I had this same problem with Google Sheets, and actually switched to using Safari with Google sheets for a while until I realized that this extension was causing the problem. Is there any way to whitelist Sheets by default so that it doesn't mysteriously break when using this extension?

**Comment by aaronraimist** [comment]
@michaelrkn if you are on version 2.3 all sites are whitelisted by default, the only place where the add-on is active is on sites you specifically blacklist.

**Comment by jswanner** [comment]
@michaelrkn: if you open a tab to chrome://extensions/?options=nkgllhigpcljnhoakjkgaieabnkmgdkb, what rules do you see? One of those rules must be matching https://docs.google.com.

**Comment by jswanner** [comment]
Alternatively, from a tab on Google Sheets: you can click on the button for this extension, a popup will open, and if there's a rule that's matching the tab's URL there will be an `x` to the right of the input field, which you can click to delete the rule.

**Comment by michaelrkn** [comment]
Weird, I don't see any rules. I'm on 2.3. I actually disabled it on Google
Sheets by clicking the extension button, seeing no rules, clicking the x,
and then refreshing the page. That doesn't sound like the expected behavior.

**Comment by jswanner** [comment]
What if you disable the extension altogether from chrome://extensions ?

**Comment by klepper** [comment]
I don't have any rules, and even if I add one for docs.google.com it still has the same no-paste in google sheet's problem.  It's blue in the icon. As soon as I disable the extension, and refresh the google sheets, I can paste again.

**Comment by michaelrkn** [comment]
I tried uninstalling and reinstalling the extension. Now it seems to have the expected behavior of being disabled by default.

**Comment by danielsamuels** [comment]
I had the same problem - no rules defined but I still couldn't paste.  Ended up simply disabling the extension and things are working again.
