### ISSUE TITLE
Permissions Update

### ISSUE THREAD

**Issue by shackrock** [jswanner/DontFuckWithPaste#60]
I was notifed today (after an auto update) that the extension now requires permissions to read browser history.  I am curious what the benefit of this is, and why it was changed?  The extension worked flawlessly in the previous version, and is this really necessary?  There is also a ton of negative feedback beginning to flow in on the Chrome Store: https://chrome.google.com/webstore/detail/dont-fuck-with-paste/nkgllhigpcljnhoakjkgaieabnkmgdkb/reviews?hl=en

Thanks for the information.  In the meantime, I have uninstalled this. 

I know this is open source, and I know that developers can review the code to see what's going on - but for the vast majority of users, they are not capable of understanding the code and thus, not requiring such permission at all is a better option.

**Comment by jswanner** [comment]
I tried to explain the reason for the increased permissions in several places:

- The extension page on [Chrome Web Store](https://chrome.google.com/webstore/detail/dont-fuck-with-paste/nkgllhigpcljnhoakjkgaieabnkmgdkb)
- The [README](https://github.com/jswanner/DontFuckWithPaste/blob/master/README.md#version-2-upgrade)
- There's a [Wiki page](https://github.com/jswanner/DontFuckWithPaste/wiki/Version-2.0) that's linked to from a notification which is displayed after the upgrade

> The extension worked flawlessly in the previous version, and is this really necessary?

It certainly wasn't a flawless experience for all the people that created issues for the previous version. If you installed the extension and never changed its default configuration, it was probably causing more harm than good, you just may not have known it.

**Comment by jswanner** [comment]
I certainly agree people should take security seriously. Being an open source extension, you are always welcome to review the code to see how this extension works, and what it's doing with your data. Alternatively, you can download the code and install locally, which would provide isolation from future updates without you explicitly upgrading the local extension.

You should probably know that "tabs" permission is not required for an extension to track all your browsing history -- no additional permission is needed beyond extension installation. So, if you are seriously concerned about extensions tracking your browsing history, you really should uninstall all extensions.
