### ISSUE TITLE
Not working with majorgeeks.com since yesterday

### ISSUE THREAD

**Issue by Adriano0312** [jswanner/DontFuckWithPaste#61]
Not working with majorgeeks.com since yesterday.

**Thanks A LOT for this extension!!**

**Comment by jswanner** [comment]
@Adriano0312 sorry to hear you are having trouble with this extension.

Can you be more specific about what's not working?

**Comment by jswanner** [comment]
I'm not sure what part of their site is blocking paste. Their login & signup forms for their forums do not, nor do the comment forms on the rest of the site. If you can be more specific, I can look into further.
