### ISSUE TITLE
Breaks image paste on Facebook

### ISSUE THREAD

**Issue by alexboutros** [jswanner/DontFuckWithPaste#64]
Chrome version: 65.0.3325.181 (Official Build) (64-bit

Don't Fuck With Paste Version: 2.3

Cannot paste images from clipboard in new posts or in messenger.

**Comment by maximbaz** [comment]
Uff, I experienced the same issue on github for a week now, apparently the extension was active because I had an empty rule (and it matched all websites?). Not sure how I ended up with the empty rule, the extension doesn't allow creating an empty one, maybe it happened during an upgrade.

**Comment by jswanner** [comment]
Ah, right, an empty rule would match anything. The following evaluates to true:

```js
(new RegExp('')).test('anything')
```

I should be able to make some changes to better prevent empty rules from being created, and can definitely skip evaluating empty patterns.

**Comment by jswanner** [comment]
I just released version 2.4 which includes fixes for empty rules.

**Comment by jswanner** [comment]
I believe I've fixed the issue @maximbaz brought up.

@alexboutros, if that didn't fix your problem, feel free to reopen this issue.
