### ISSUE TITLE
Not working in Axis Bank site (https://retail.axisbank.co.in/wps/portal/rBanking/axisebanking/AxisRetailLogin/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOKNAzxMjIwNjLwsQp0MDBw9PUOd3HwdDQwMjIEKIoEKDHAARwNC-sP1o_ArMYIqwGNFQW6EQaajoiIAVNL82A!!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/)

### ISSUE THREAD

**Issue by senguttuvang** [jswanner/DontFuckWithPaste#68]
I have both Don't fuck with paste and Allow right click and I tried with both Command + v, right click and the Edit menu. None of them seems to be working here. Generate password option from Chrome is working, though. Any idea how I can work around this?

Axis Bank link: https://retail.axisbank.co.in/wps/portal/rBanking/axisebanking/AxisRetailLogin/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOKNAzxMjIwNjLwsQp0MDBw9PUOd3HwdDQwMjIEKIoEKDHAARwNC-sP1o_ArMYIqwGNFQW6EQaajoiIAVNL82A!!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/

**Comment by jswanner** [comment]
@senguttuvang, sorry you are having trouble, thanks for informing me of it.

The extension is working with Axis Bank. But, I did find a bug: if you have multiple windows open, when you add a rule, it doesn't always check the active tab in the current window to see if the extension should be active or not. You can ensure that active check is run for your current tab by refreshing the page or switching to another tab and then back.

I'll be releasing an update to the extension to fix the bug, but the above is a work-around in the mean time.

Demo of the work-around:

![axis-dfwp](https://user-images.githubusercontent.com/261/43601849-254789fa-9643-11e8-8ba5-38537839a12a.gif)

You can see the extension's icon doesn't turn blue until after page refresh.

**Comment by jswanner** [comment]
Extension update has been published, you can force the upgrade by going to `chrome://extensions` and clicking "Update"
