### ISSUE TITLE
Facebook issue 

### ISSUE THREAD

**Issue by mightyuhu** [jswanner/DontFuckWithPaste#7]
There seems to be an issue with facebook and this extension:

Whenever you paste something into a post or comment , the posted text appears twice.

Other than that great extension keep it up!

**Comment by mightyuhu** [comment]
I researched this and it seems facebook/react.js does not use an html input/textarea-tag but rather implement their own textarea-like behavior using all kind of magic. This makes the focussed element receive a "paste"-event as well as a "ctrl-v". Facebook handles only the ctrl-v one and ignores the paste-event, which is prevented by this extension, with the effect that the paste is executed twice.

A fix would be to only capture this events on actual input fields i.e.  changing the implementation to
`  if(e.srcElement.nodeName == "INPUT" || e.srcElement.nodeName == "TEXTAREA")
    e.stopImmediatePropagation();
`
or add facebook to the list of ignored sites

**Comment by jswanner** [comment]
I've disabled the extension on the facebook.com domain, I would much rather have a user-configurable settings, but this is a band-aid until then.

I'm just waiting for the Chrome Web Store to publish the new version.

**Comment by jswanner** [comment]
A new version of this extension has been pushed, which includes user-configurable settings for which sites this extension should run on.
