### ISSUE TITLE
Extension Disabled on Chrome

### ISSUE THREAD

**Issue by LenieaKea** [jswanner/DontFuckWithPaste#70]
Hi! I have been using the extension for a few weeks now, and it works great, but now suddensly its not working anymore, and when i checked it says that it has been diasbled on Chrome. When i try to enable it nothing happens at all. Can this be fixed?

**Comment by Sushubh** [comment]
developer seems to have released a new version where you opt-in to individual domains. so new permissions are required. for me it let me enable it manually. maybe try uninstalling and reinstalling?

**Comment by jswanner** [comment]
Please see https://github.com/jswanner/DontFuckWithPaste/wiki/Version-2.0#usage
