### ISSUE TITLE
Eversource website blocks paste

### ISSUE THREAD

**Issue by nitrocode** [jswanner/DontFuckWithPaste#71]
I noticed on the [Eversource registration](https://www.eversource.com/security/Account/Register) page, it blocks pasting passwords.

I tried the Edit > Paste suggestion from issue #69 and it still didn't work. 

@jswanner What do you think is the issue? I'll try to investigate when I have some time. Thanks for a very helpful extension.

On sites like the ones above, I switch to Firefox because it has the option to disable clipboard events by setting `dom.event.clipboardevents.enabled` to `false`. Chrome still doesn't have this option... :roll_eyes:

**Comment by jswanner** [comment]
@nitrocode, sorry you are having trouble.

I see how they are blocking paste (lines 378-382 of https://www.eversource.com/security/Scripts/Utility.js), they are using jQuery to bind to `paste` events and then calling `preventDefault` on the event; precisely the kind of thing this extension is meant to handle.

And in fact, once I active the extension for that site, I'm able to paste into the password field. When you on that site, what color is the icon for this extension, grey or blue? If grey, please see https://github.com/jswanner/DontFuckWithPaste/wiki/Version-2.0#usage for help.

**Comment by nitrocode** [comment]
@jswanner ah I cannot follow directions... I kept thinking the extension would automatically look for paste events and apply the correct overriding javascript. I didn't realize I had to add the site to a blacklist. 

Do you think you could allow for an option to automatically scan each page I visit and inject the overriding code? This is how ublockorigin, nanoadblocker, nanodefender, etc work.

I could put that request in a separate ticket if you like.

**Comment by jswanner** [comment]
@nitrocode, unfortunately, browsers do not expose information about attach event listeners. So, there’s no great option to scan the page in order to determine if it should automatically activate. 

Note: Chrome DevTools has a `getEventListeners(object)` function, but it’s only available in the developer console, can’t use it in scripts.
