### ISSUE TITLE
Does not seem to work on this site

### ISSUE THREAD

**Issue by zeoce** [jswanner/DontFuckWithPaste#76]
https://idp.gvfv.clareitysecurity.net/idp/Authn/UserPassword

I believe the extension is activated (turns blue). The error message: "you must enter your password manually come up"

Any ideas?

**Comment by jswanner** [comment]
@zeoce, by default, that site blocks `paste` events, this extension correctly circumvents their blocking. Unfortunately, they have a separate `keyup` event listener, which they use to keep track of how many keys you've pressed for that field, and they show that "you must enter your password manually" message unless you press more than 3 keys. They also clear out the field's value if you press certain keys or key combinations. A whole bunch of weird things.

You yourself can circumvent that `keyup` listener by pressing a letter then backspace, then repeat that sequence again, then paste. Super annoying.

I don't want this extension getting involved with keyboard and mouse events, it can already cause problems with just copy/cut/paste events.

You are probably better off using something like Tampermonkey to prevent that site from hooking into keyboard events.

**Comment by zeoce** [comment]
Thank you so much for looking into it! I will look into utilizing tampermonkey.

Cheers :)
