### ISSUE TITLE
Can't paste images on WhatsApp nor Slack

### ISSUE THREAD

**Issue by TheRealNox** [jswanner/DontFuckWithPaste#88]
When this extension is enabled on all site, I can't paste images (from example after a screen-grab) onto whatsapp or slack.

**Comment by jswanner** [comment]
@TheRealNox,

I do not recommend having the extension active on all sites. Having the extension active on sites that do helpful things with copy and paste events (like GitHub, Slack and many others) will lead to a degraded browsing experience. That's exactly why with version 2 of this extension it is not active on all sites by default and I tried to make it was easy as possible to make the extension active only on the offending sites that you encounter.
