### ISSUE TITLE
california dmv website actively ducking this extension

### ISSUE THREAD

**Issue by Viss** [jswanner/DontFuckWithPaste#91]
if you go to www.dmv.ca.gov and you click through the pages to renew your california drivers license, you get to a page that asks you to create an account. They're using javascript to block the pressing of the control button, and right click:

![image](https://user-images.githubusercontent.com/1756255/63203024-c7dbf880-c041-11e9-98b6-1f74e164453b.png)

I've tried using this extension and adding dmv.ca.gov but it doesnt seem to help. 
I've also tried manually removing the javascript using the chrome inspector tools, but it somehow 'just comes back'.

**Comment by jswanner** [comment]
@Viss, I can confirm what you're experiencing. This extension is meant to prevent sites from blocking the `copy`, `cut`, and`paste` browser events directly. There are several ways in which those events are triggered by browsers: keyboard shortcuts, via context menu (right-click), and through the browser's Edit menu. This extension intentionally does not try to stop sites from blocking paste via keyboard shortcuts nor context menu, as that's a messy rabbit hole to go down and it would probably break more things then it fixed.

You actually don't need to activate this extension for that site, as you can paste from the browser's Edit -> Paste menu option. Some sites would require you to activate the extension before that would work, but not the site in question.

I know using the Edit menu is not as convenient as using the keyboard shortcut, but at least it still allows pasting text. I wish sites didn't interfere with normal browsing behavior.

**Comment by jswanner** [comment]
> I've also tried manually removing the javascript using the chrome inspector tools, but it somehow 'just comes back'.

Unfortunately, just removing the attribute from the Elements pane of the dev tools doesn't really remove the event listener. If you click on the element, then in the Console pane, you can remove it with `$0.onkeydown = null`.
