### ISSUE TITLE
Large file included in xpi

### ISSUE THREAD

**Issue by emperlium** [jswanner/DontFuckWithPaste#92]
Version 2.3.1 of the xpi at addons.mozilla.org contains a rather large file called package-lock.json.

I can't find that in Github nor any mention when greping the code. Was it included accidentally or does it serve a purpose?

**Comment by jswanner** [comment]
@emperlium, I don't publish this extension as a Firefox addon. I believe it's this fork that you are interested in: https://github.com/aaronraimist/DontFuckWithPaste
