### ISSUE TITLE
DFW Find

### ISSUE THREAD

**Issue by brianegge** [jswanner/DontFuckWithPaste#96]
Is there any facility to disable sites which hijack find? Seems the work around is to put the cursor in the URL bar, then press ⌘-F. Some sites hijack it to replace it with some broken search. I.e., https://community.octoprint.org/t/available-mjpg-streamer-configuration-options/1106

**Comment by jswanner** [comment]
@brianegge, this extension doesn't support that kind of intervention. I would look into [TamperMonkey](https://www.tampermonkey.net/) for something like that.
